export enum QueryKeysEnum {
  COINGECKO_COIN = 'coingecko_coin',
  COINGECKO_COIN_HISTORIES = 'coingecko_coin_histories',
  ACCOUNT_PUBLIC_KEYS = 'account_public_keys',
  ACCOUNTS = 'accounts',
  ACCOUNT = 'account',
  RECOVERY_PHRASE = 'recovery_phrase',
  MY_TOKENS = 'tokens',
  TOKEN = 'token',
  CURRENT_ACCOUNT = 'current_account',
  ASSETS = 'assets',
  COIN_BALANCE = 'coin_balance',
  TRANSACTION_HISTORIES = 'transaction_histories',
  CONNECTED_URLS = 'connected_urls',
  CONNECTED_URL = 'connected_url',
  PARSED_DEPLOY_DATA = 'parsed_deploy_data',
  CSPR_PRICE = 'cspr_price',
  PRICE_HISTORIES = 'price_histories',
  NFTS = 'nfts',
  PRIVATE_KEY_WITH_UID = 'private_key_with_uid',
}
