name: Deploy Testnet

on:
  push:
    branches: [ ci/deploy-testnet ]

jobs:
  deploy-testnet:
    runs-on: ubuntu-latest

    strategy:
        matrix:
            node-version: [18]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
            cache: 'yarn'
            node-version: ${{ matrix.node-version }}
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
            cmd: install
      - name: Cache node_modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: |
            node_modules
          key: modules-${{ hashFiles('yarn.lock') }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1


      - name: build
        run : |
            yarn build

      - name: Publish docs to S3
        uses: eisberg-labs/static-website-to-s3@main
        with:
          target: dist
          dest: ./
          exclusions: dist\/(index|404).html$
          bucket: testnet.casperdash.io
