name: Publish docs

on:
  push:
    branches: [ main ]
    tags:
      - docs-*

jobs:
  publish-docs:
    runs-on: ubuntu-latest

    strategy:
        matrix:
            node-version: [18]
            pnpm-version: [7.26.3]

    steps:
      - uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
            cache: 'pnpm'
            node-version: ${{ matrix.node-version }}
      - name: Install
        run : |
            pnpm i
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Export docs
        run : |
          pnpm docs:export

      - name: Publish docs to S3
        uses: eisberg-labs/static-website-to-s3@main
        with:
          target: docs/out
          dest: deploy
          exclusions: docs\/out\/(index|404).html$
          bucket: casper-web.casperdash.io
